version: '3.1'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password       # CHANGE THE PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/my.cnf

  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080                       # ACCESS ON WEB http://host:80

volumes:
  db_data:
